baseURL: https://davide.im/
languageCode: en-us
title: Davide Ferrari
paginate: 5
theme: "PaperMod"

enableRobotsTXT: true
enableEmoji: true

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
  env: production
  title: Davide Ferrari
  description: "Davide Ferrari's personal portfolio website and blog"
  keywords: [Blog, Portfolio, Software, dotnet, Flutter]
  images: ["https://avatars.githubusercontent.com/u/23432883"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light

  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  comments: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/favicon.png"
    favicon16x16: "/favicon16.png"
    favicon32x32: "/favicon32.png"
    apple_touch_icon: "/clipimage.png"
    #safari_pinned_tab: "<link / abs url>"

  homeInfoParams:
    Title: Davide Ferrari
    Content: obsessed software dev with a messed up sleep cycle
      

  socialIcons:
        - name: x
          url: "https://x.com/frrdavide"
        - name: instagram
          url: "https://www.instagram.com/davideferrari.py"
        - name: telegram
          url: "https://t.me/ferraridavide"
        - name: github
          url: "https://github.com/ferraridavide"
        - name: linkedin
          url: "https://www.linkedin.com/in/frrdavide/"
        - name: email
          url: "mailto:davideferrari.bns@gmail.com"
        - name: key
          url: /davideferrari.asc
        
  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - name: Skills
      params:
        icon: "📚"
      url: skills/
      weight: 15
    - name: Updates
      params:
        icon: "📅"
      url: updates/
      weight: 20
    - name: Flying
      params:
        icon: "🪂"
      url: flying/
      weight: 25
